// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using forzion.tech.Infrastructure.Persistence;

#nullable disable

namespace forzion.tech.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525214007_AdicionarEmailDeliveryLogs")]
    partial class AdicionarEmailDeliveryLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("homolog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiasDisponiveis")
                        .HasColumnType("integer")
                        .HasColumnName("dias_disponiveis");

                    b.Property<string>("Doencas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("doencas");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Finalidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("finalidade");

                    b.Property<string>("FocoTreino")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("foco_treino");

                    b.Property<string>("LimitacoesFisicas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("limitacoes_fisicas");

                    b.Property<string>("NivelCondicionamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nivel_condicionamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("ObservacoesAdicionais")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_adicionais");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<int?>("TempoDisponivelMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_disponivel_minutos");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_alunos_conta_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_alunos_status");

                    b.ToTable("alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Assinante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assinantes");

                    b.HasIndex("AlunoId")
                        .IsUnique()
                        .HasDatabaseName("ix_assinantes_aluno_id");

                    b.ToTable("assinantes", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.AssinaturaAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime>("DataProximaCobranca")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_proxima_cobranca");

                    b.Property<Guid>("PacoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<Guid>("VinculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("vinculo_id");

                    b.HasKey("Id")
                        .HasName("pk_assinaturas_aluno");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_assinaturas_aluno_aluno_id");

                    b.HasIndex("PacoteId")
                        .HasDatabaseName("ix_assinaturas_aluno_pacote_id");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_assinaturas_aluno_treinador_id");

                    b.HasIndex("VinculoId")
                        .IsUnique()
                        .HasDatabaseName("ix_assinaturas_aluno_vinculo_id");

                    b.HasIndex("Status", "DataProximaCobranca")
                        .HasDatabaseName("ix_assinaturas_aluno_status_data_proxima_cobranca");

                    b.ToTable("assinaturas_aluno", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_conta");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_email");

                    b.ToTable("contas", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ContaRecebimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("OnboardingCompleto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("onboarding_completo");

                    b.Property<string>("StripeConnectAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stripe_connect_account_id");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conta_recebimento");

                    b.HasIndex("StripeConnectAccountId")
                        .HasDatabaseName("ix_conta_recebimento_stripe_connect_account_id");

                    b.HasIndex("TreinadorId")
                        .IsUnique()
                        .HasDatabaseName("ix_conta_recebimento_treinador_id");

                    b.ToTable("conta_recebimento", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.EmailDeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("ResendMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resend_message_id");

                    b.HasKey("Id")
                        .HasName("pk_email_delivery_logs");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_email_delivery_logs_event_type");

                    b.HasIndex("ResendMessageId")
                        .HasDatabaseName("ix_email_delivery_logs_resend_message_id");

                    b.ToTable("email_delivery_logs", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CargaExecutada")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga_executada");

                    b.Property<Guid>("ExecucaoTreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("execucao_treino_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("RepeticoesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes_executadas");

                    b.Property<int>("SeriesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("series_executadas");

                    b.Property<Guid>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_exercicio");

                    b.HasIndex("ExecucaoTreinoId")
                        .HasDatabaseName("ix_execucoes_exercicio_execucao_treino_id");

                    b.HasIndex("TreinoExercicioId")
                        .HasDatabaseName("ix_execucoes_exercicio_treino_exercicio_id");

                    b.ToTable("execucoes_exercicio", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_execucao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_treino");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_execucoes_treino_aluno_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_execucoes_treino_treino_id");

                    b.ToTable("execucoes_treino", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("GrupoMuscularId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_muscular_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercicios");

                    b.HasIndex("GrupoMuscularId")
                        .HasDatabaseName("ix_exercicios_grupo_muscular_id");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_exercicios_treinador_id");

                    b.ToTable("exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grupos_musculares");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_musculares_nome");

                    b.ToTable("grupos_musculares", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.LogAprovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_tipo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("RealizadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("realizado_por_id");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_acao");

                    b.HasKey("Id")
                        .HasName("pk_logs_aprovacao");

                    b.HasIndex("EntidadeId")
                        .HasDatabaseName("ix_logs_aprovacao_entidade_id");

                    b.HasIndex("RealizadoPorId")
                        .HasDatabaseName("ix_logs_aprovacao_realizado_por_id");

                    b.ToTable("logs_aprovacao", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Pacote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacotes");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_pacotes_treinador_id");

                    b.ToTable("pacotes", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssinaturaAlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("assinatura_aluno_id");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pix")
                        .HasColumnName("metodo_pagamento");

                    b.Property<DateTime?>("PixExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pix_expiracao");

                    b.Property<string>("PixQrCode")
                        .HasColumnType("text")
                        .HasColumnName("pix_qr_code");

                    b.Property<string>("PixQrCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pix_qr_code_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos");

                    b.HasIndex("AssinaturaAlunoId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagamentos_assinatura_aluno_id_pendente_unique")
                        .HasFilter("status = 'Pendente'");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagamentos_stripe_payment_intent_id");

                    b.HasIndex("AssinaturaAlunoId", "Status")
                        .HasDatabaseName("ix_pagamentos_assinatura_aluno_id_status");

                    b.ToTable("pagamentos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_password_reset_tokens_conta_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.ToTable("password_reset_tokens", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.PlanoPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ativo");

                    b.Property<int>("MaxAlunos")
                        .HasColumnType("integer")
                        .HasColumnName("max_alunos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_planos_plataforma");

                    b.ToTable("planos_plataforma", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SerieConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Carga")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga");

                    b.Property<int?>("Descanso")
                        .HasColumnType("integer")
                        .HasColumnName("descanso");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int?>("RepeticoesMax")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes_max");

                    b.Property<int>("RepeticoesMin")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes_min");

                    b.Property<Guid>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.HasKey("Id")
                        .HasName("pk_treino_exercicio_series");

                    b.HasIndex("TreinoExercicioId")
                        .HasDatabaseName("ix_treino_exercicio_series_treino_exercicio_id");

                    b.ToTable("treino_exercicio_series", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_users");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_system_users_conta_id");

                    b.ToTable("system_users", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TokenRevogado", b =>
                {
                    b.Property<Guid>("Jti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.HasKey("Jti")
                        .HasName("pk_tokens_revogados");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("ix_tokens_revogados_expira_em");

                    b.ToTable("tokens_revogados", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprovado_em");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovado_por_id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("PlanoPlataformaId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_plataforma_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treinadores");

                    b.HasIndex("ContaId")
                        .IsUnique()
                        .HasDatabaseName("ix_treinadores_conta_id");

                    b.HasIndex("PlanoPlataformaId")
                        .HasDatabaseName("ix_treinadores_plano_plataforma_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_treinadores_status");

                    b.ToTable("treinadores", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Iniciante")
                        .HasColumnName("dificuldade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treinos");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_treinos_treinador_id");

                    b.ToTable("treinos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treino_alunos");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_treino_alunos_aluno_id");

                    b.HasIndex("TreinoId")
                        .IsUnique()
                        .HasDatabaseName("ix_treino_alunos_treino_id")
                        .HasFilter("status = 'Ativo'");

                    b.ToTable("treino_alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercicio_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_treino_exercicios");

                    b.HasIndex("ExercicioId")
                        .HasDatabaseName("ix_treino_exercicios_exercicio_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_treino_exercicios_treino_id");

                    b.ToTable("treino_exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.VinculoTreinadorAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprovado_em");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovado_por_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid?>("PacoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacote_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.HasKey("Id")
                        .HasName("pk_vinculos_treinador_aluno");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_aluno_id");

                    b.HasIndex("PacoteId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_pacote_id");

                    b.HasIndex("TreinadorId", "AlunoId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_treinador_id_aluno_id");

                    b.HasIndex("TreinadorId", "Status")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_treinador_id_status");

                    b.ToTable("vinculos_treinador_aluno", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_contas_conta_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.AssinaturaAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_aluno_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Pacote", null)
                        .WithMany()
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_aluno_pacotes_pacote_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_aluno_treinadores_treinador_id");

                    b.HasOne("forzion.tech.Domain.Entities.VinculoTreinadorAluno", null)
                        .WithMany()
                        .HasForeignKey("VinculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_aluno_vinculos_treinador_aluno_vinculo_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ContaRecebimento", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conta_recebimento_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.ExecucaoTreino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("ExecucaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_execucoes_treino_execucao_treino_id");

                    b.HasOne("forzion.tech.Domain.Entities.TreinoExercicio", null)
                        .WithMany()
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_treino_exercicios_treino_exercicio_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.GrupoMuscular", null)
                        .WithMany()
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercicios_grupos_musculares_grupo_muscular_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exercicios_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Pacote", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pacotes_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.AssinaturaAluno", null)
                        .WithMany()
                        .HasForeignKey("AssinaturaAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_assinaturas_aluno_assinatura_aluno_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SerieConfig", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.TreinoExercicio", null)
                        .WithMany("Series")
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicio_series_treino_exercicios_treino_exercicio_");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SystemUser", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_users_contas_conta_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treinador", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinadores_contas_conta_id");

                    b.HasOne("forzion.tech.Domain.Entities.PlanoPlataforma", null)
                        .WithMany()
                        .HasForeignKey("PlanoPlataformaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_treinadores_planos_plataforma_plano_plataforma_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinos_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Exercicio", null)
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_exercicios_exercicio_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.VinculoTreinadorAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_treinador_aluno_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Pacote", null)
                        .WithMany()
                        .HasForeignKey("PacoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vinculos_treinador_aluno_pacotes_pacote_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_treinador_aluno_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
