// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using forzion.tech.Infrastructure.Persistence;

#nullable disable

namespace forzion.tech.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501233811_RemoverMaxFichasAdicionarDescricaoPacote")]
    partial class RemoverMaxFichasAdicionarDescricaoPacote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("homolog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_alunos_conta_id");

                    b.ToTable("alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("TipoConta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_conta");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_contas");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_contas_email");

                    b.ToTable("contas", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CargaExecutada")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga_executada");

                    b.Property<Guid>("ExecucaoTreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("execucao_treino_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("RepeticoesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes_executadas");

                    b.Property<int>("SeriesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("series_executadas");

                    b.Property<Guid>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_exercicio");

                    b.HasIndex("ExecucaoTreinoId")
                        .HasDatabaseName("ix_execucoes_exercicio_execucao_treino_id");

                    b.HasIndex("TreinoExercicioId")
                        .HasDatabaseName("ix_execucoes_exercicio_treino_exercicio_id");

                    b.ToTable("execucoes_exercicio", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_execucao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_treino");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_execucoes_treino_aluno_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_execucoes_treino_treino_id");

                    b.ToTable("execucoes_treino", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_muscular");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercicios");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_exercicios_treinador_id");

                    b.ToTable("exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.GrupoMuscular", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grupos_musculares");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_musculares_nome");

                    b.ToTable("grupos_musculares", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.LogAprovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade_tipo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("RealizadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("realizado_por_id");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_acao");

                    b.HasKey("Id")
                        .HasName("pk_logs_aprovacao");

                    b.HasIndex("EntidadeId")
                        .HasDatabaseName("ix_logs_aprovacao_entidade_id");

                    b.HasIndex("RealizadoPorId")
                        .HasDatabaseName("ix_logs_aprovacao_realizado_por_id");

                    b.ToTable("logs_aprovacao", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.PacoteAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pacotes_aluno");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_pacotes_aluno_treinador_id");

                    b.ToTable("pacotes_aluno", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.PlanoTreinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ativo");

                    b.Property<int>("MaxAlunos")
                        .HasColumnType("integer")
                        .HasColumnName("max_alunos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_planos_treinador");

                    b.ToTable("planos_treinador", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_system_users");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("ix_system_users_conta_id");

                    b.ToTable("system_users", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treinador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprovado_em");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovado_por_id");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("PlanoTreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_treinador_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treinadores");

                    b.HasIndex("ContaId")
                        .IsUnique()
                        .HasDatabaseName("ix_treinadores_conta_id");

                    b.HasIndex("PlanoTreinadorId")
                        .HasDatabaseName("ix_treinadores_plano_treinador_id");

                    b.ToTable("treinadores", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treinos");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_treinos_treinador_id");

                    b.ToTable("treinos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treino_alunos");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_treino_alunos_aluno_id");

                    b.HasIndex("TreinoId")
                        .IsUnique()
                        .HasDatabaseName("ix_treino_alunos_treino_id")
                        .HasFilter("status = 'Ativo'");

                    b.ToTable("treino_alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Carga")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga");

                    b.Property<int?>("Descanso")
                        .HasColumnType("integer")
                        .HasColumnName("descanso");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercicio_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes");

                    b.Property<int>("Series")
                        .HasColumnType("integer")
                        .HasColumnName("series");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_treino_exercicios");

                    b.HasIndex("ExercicioId")
                        .HasDatabaseName("ix_treino_exercicios_exercicio_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_treino_exercicios_treino_id");

                    b.ToTable("treino_exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.VinculoTreinadorAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aprovado_em");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovado_por_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid?>("PacoteAlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pacote_aluno_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.HasKey("Id")
                        .HasName("pk_vinculos_treinador_aluno");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_aluno_id");

                    b.HasIndex("PacoteAlunoId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_pacote_aluno_id");

                    b.HasIndex("TreinadorId", "AlunoId")
                        .HasDatabaseName("ix_vinculos_treinador_aluno_treinador_id_aluno_id");

                    b.ToTable("vinculos_treinador_aluno", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_contas_conta_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.ExecucaoTreino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("ExecucaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_execucoes_treino_execucao_treino_id");

                    b.HasOne("forzion.tech.Domain.Entities.TreinoExercicio", null)
                        .WithMany()
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_treino_exercicios_treino_exercicio_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_exercicios_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.PacoteAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pacotes_aluno_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.SystemUser", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_users_contas_conta_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treinador", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Conta", null)
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinadores_contas_conta_id");

                    b.HasOne("forzion.tech.Domain.Entities.PlanoTreinador", null)
                        .WithMany()
                        .HasForeignKey("PlanoTreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_treinadores_planos_treinador_plano_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinos_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_exercicios_exercicio_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_treinos_treino_id");

                    b.Navigation("Exercicio");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.VinculoTreinadorAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_treinador_aluno_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.PacoteAluno", null)
                        .WithMany()
                        .HasForeignKey("PacoteAlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vinculos_treinador_aluno_pacotes_aluno_pacote_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treinador", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_treinador_aluno_treinadores_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
