// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using forzion.tech.Infrastructure.Persistence;

#nullable disable

namespace forzion.tech.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416131412_AddRlsTreinosEExercicios")]
    partial class AddRlsTreinosEExercicios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("homolog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_alunos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_alunos_tenant_id");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_alunos_treinador_id");

                    b.ToTable("alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CargaExecutada")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga_executada");

                    b.Property<Guid>("ExecucaoTreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("execucao_treino_id");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("RepeticoesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes_executadas");

                    b.Property<int>("SeriesExecutadas")
                        .HasColumnType("integer")
                        .HasColumnName("series_executadas");

                    b.Property<Guid>("TreinoExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_exercicio_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_exercicio");

                    b.HasIndex("ExecucaoTreinoId")
                        .HasDatabaseName("ix_execucoes_exercicio_execucao_treino_id");

                    b.HasIndex("TreinoExercicioId")
                        .HasDatabaseName("ix_execucoes_exercicio_treino_exercicio_id");

                    b.ToTable("execucoes_exercicio", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_execucao");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_treino");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_execucoes_treino_aluno_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_execucoes_treino_tenant_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_execucoes_treino_treino_id");

                    b.ToTable("execucoes_treino", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_muscular");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_exercicios");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_exercicios_tenant_id");

                    b.ToTable("exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("integer")
                        .HasColumnName("limite_alunos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id")
                        .HasName("pk_planos");

                    b.ToTable("planos", "homolog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsFree = true,
                            LimiteAlunos = 5,
                            Nome = "Free",
                            Preco = 0m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsFree = false,
                            LimiteAlunos = 2147483647,
                            Nome = "Pro",
                            Preco = 49.90m
                        });
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("ix_tenants_plano_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TreinadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("treinador_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treinos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_treinos_tenant_id");

                    b.HasIndex("TreinadorId")
                        .HasDatabaseName("ix_treinos_treinador_id");

                    b.ToTable("treinos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid")
                        .HasColumnName("aluno_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_treino_alunos");

                    b.HasIndex("AlunoId")
                        .HasDatabaseName("ix_treino_alunos_aluno_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_treino_alunos_treino_id");

                    b.ToTable("treino_alunos", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Carga")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carga");

                    b.Property<int?>("Descanso")
                        .HasColumnType("integer")
                        .HasColumnName("descanso");

                    b.Property<Guid>("ExercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercicio_id");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Repeticoes")
                        .HasColumnType("integer")
                        .HasColumnName("repeticoes");

                    b.Property<int>("Series")
                        .HasColumnType("integer")
                        .HasColumnName("series");

                    b.Property<Guid>("TreinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("treino_id");

                    b.HasKey("Id")
                        .HasName("pk_treino_exercicios");

                    b.HasIndex("ExercicioId")
                        .HasDatabaseName("ix_treino_exercicios_exercicio_id");

                    b.HasIndex("TreinoId")
                        .HasDatabaseName("ix_treino_exercicios_treino_id");

                    b.ToTable("treino_exercicios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_usuarios_tenant_id");

                    b.ToTable("usuarios", "homolog");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_tenants_tenant_id");

                    b.HasOne("forzion.tech.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alunos_usuarios_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.ExecucaoTreino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("ExecucaoTreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_execucoes_treino_execucao_treino_id");

                    b.HasOne("forzion.tech.Domain.Entities.TreinoExercicio", null)
                        .WithMany()
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_exercicio_treino_exercicio_treino_exercicio_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_treino_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Exercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercicios_tenants_tenant_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_planos_plano_id");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinos_tenants_tenant_id");

                    b.HasOne("forzion.tech.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treinos_usuarios_treinador_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoAluno", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_alunos_aluno_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany()
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_alunos_treinos_treino_id");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.TreinoExercicio", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Exercicio", "Exercicio")
                        .WithMany()
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_exercicios_exercicio_id");

                    b.HasOne("forzion.tech.Domain.Entities.Treino", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_treino_exercicios_treinos_treino_id");

                    b.Navigation("Exercicio");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("forzion.tech.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.ExecucaoTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("forzion.tech.Domain.Entities.Treino", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
